services:
  - type: web
    name: fantaf1
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"
