# Generated by Django 4.2.23 on 2025-07-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0008_rename_type_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='championship',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playerentry',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='fantaApp.championship'),
        ),
        migrations.AlterField(
            model_name='playerentry',
            name='league',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='fantaApp.league'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='championship',
            unique_together={('name', 'year')},
        ),
    ]
