# Generated by Django 4.2.23 on 2025-07-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0009_championship_active_championship_is_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerentry',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='fantaApp.league'),
        ),
    ]
