# Generated by Django 4.2.23 on 2025-07-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0010_alter_playerentry_league'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerEntry',
            new_name='ChampionshipPlayer',
        ),
    ]
