# Generated by Django 4.2.23 on 2025-07-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0015_rename_spinr_qualifing_start_race_sprint_qualifying_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='active',
        ),
    ]
