# Generated by Django 4.2.23 on 2025-07-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0016_remove_circuit_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='event_name',
            field=models.CharField(default='prova', max_length=100),
            preserve_default=False,
        ),
    ]
