# Generated by Django 4.2.23 on 2025-07-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0017_race_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='round_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='race',
            name='week',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='race',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
