# Generated by Django 4.2.23 on 2025-07-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0019_alter_race_options_alter_race_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['team__name', 'first_name']},
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='driver',
            name='api_id',
            field=models.CharField(default='prova', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='api_id',
            field=models.CharField(default='prova', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
