# Generated by Django 5.2.3 on 2025-07-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0022_alter_circuit_api_id_alter_driver_api_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='season',
            field=models.PositiveSmallIntegerField(default=2025),
            preserve_default=False,
        ),
    ]
