# Generated by Django 5.2.3 on 2025-07-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0026_alter_qualifingentry_q1_position_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QualifingEntry',
            new_name='QualifyingEntry',
        ),
        migrations.AddField(
            model_name='raceentry',
            name='fast_lap',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raceentry',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='best_lap',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raceentry',
            name='status',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Retired', 'Did Not Finish'), ('Lapped', 'Lapped'), ('Disqualified', 'Disqualified'), ('Did not start', 'DNS')], max_length=20),
        ),
    ]
