# Generated by Django 5.2.3 on 2025-07-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0027_rename_qualifingentry_qualifyingentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceentry',
            name='time',
        ),
    ]
