# Generated by Django 5.2.3 on 2025-07-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0029_qualifyingentry_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Race',
            new_name='Weekend',
        ),
        migrations.AlterModelOptions(
            name='qualifyingentry',
            options={'ordering': ['weekend', 'position']},
        ),
        migrations.AlterModelOptions(
            name='raceentry',
            options={'ordering': ['weekend', 'position']},
        ),
        migrations.RenameField(
            model_name='qualifyingentry',
            old_name='race',
            new_name='weekend',
        ),
        migrations.RenameField(
            model_name='raceentry',
            old_name='race',
            new_name='weekend',
        ),
        migrations.AlterUniqueTogether(
            name='qualifyingentry',
            unique_together={('weekend', 'driver')},
        ),
        migrations.AlterUniqueTogether(
            name='raceentry',
            unique_together={('weekend', 'driver')},
        ),
    ]
