# Generated by Django 5.2.3 on 2025-07-15 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0029_qualifyingentry_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regular', 'Regular Race Qualifying'), ('sprint', 'Sprint Race Qualifying')], default='regular', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='qualifyingentry',
            options={'ordering': ['qualifying', 'position']},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={},
        ),
        migrations.RenameField(
            model_name='race',
            old_name='race_type',
            new_name='type',
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='qualifyingentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='qualifyingentry',
            name='qualifying',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qualifying_entries', to='fantaApp.qualifying'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='qualifyingentry',
            unique_together={('qualifying', 'driver')},
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('round_number', models.PositiveSmallIntegerField()),
                ('season', models.PositiveSmallIntegerField()),
                ('fp1_start', models.DateTimeField(blank=True, null=True)),
                ('fp2_start', models.DateTimeField(blank=True, null=True)),
                ('fp3_start', models.DateTimeField(blank=True, null=True)),
                ('sprint_start', models.DateTimeField(blank=True, null=True)),
                ('sprint_qualifying_start', models.DateTimeField(blank=True, null=True)),
                ('qualifying_start', models.DateTimeField(blank=True, null=True)),
                ('race_start', models.DateTimeField(blank=True, null=True)),
                ('weekend_type', models.CharField(choices=[('regular', 'Regular Race'), ('sprint', 'Sprint Race')], default='regular', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantaApp.circuit')),
            ],
            options={
                'ordering': ['season', 'round_number'],
                'unique_together': {('circuit', 'season', 'round_number')},
            },
        ),
        migrations.AddField(
            model_name='qualifying',
            name='weekend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Qualifying', to='fantaApp.weekend'),
        ),
        migrations.AddField(
            model_name='race',
            name='weekend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Race', to='fantaApp.weekend'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='race',
            name='circuit',
        ),
        migrations.RemoveField(
            model_name='race',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='race',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='race',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='race',
            name='fp1_start',
        ),
        migrations.RemoveField(
            model_name='race',
            name='fp2_start',
        ),
        migrations.RemoveField(
            model_name='race',
            name='fp3_start',
        ),
        migrations.RemoveField(
            model_name='race',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='race',
            name='qualifying_start',
        ),
        migrations.RemoveField(
            model_name='race',
            name='race_start',
        ),
        migrations.RemoveField(
            model_name='race',
            name='round_number',
        ),
        migrations.RemoveField(
            model_name='race',
            name='season',
        ),
        migrations.RemoveField(
            model_name='race',
            name='sprint_qualifying_start',
        ),
        migrations.RemoveField(
            model_name='race',
            name='sprint_start',
        ),
        migrations.RemoveField(
            model_name='qualifyingentry',
            name='race',
        ),
    ]
