# Generated by Django 4.2.23 on 2025-07-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0031_alter_weekend_weekend_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('number', 'season')},
        ),
    ]
