# Generated by Django 4.2.23 on 2025-07-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0032_alter_driver_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerQualifyingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fantaApp.driver')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantaApp.championshipplayer')),
                ('qualifying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantaApp.qualifying')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerRaceChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_pupillo', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fantaApp.driver')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantaApp.championshipplayer')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantaApp.race')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='RaceResult',
        ),
        migrations.AddIndex(
            model_name='playerracechoice',
            index=models.Index(fields=['player', 'driver'], name='fantaApp_pl_player__20a9f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerracechoice',
            unique_together={('player', 'race', 'driver')},
        ),
        migrations.AddIndex(
            model_name='playerqualifyingchoice',
            index=models.Index(fields=['player', 'driver'], name='fantaApp_pl_player__ab0528_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerqualifyingchoice',
            unique_together={('player', 'qualifying')},
        ),
    ]
