# Generated by Django 4.2.23 on 2025-07-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0036_alter_race_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualifying',
            options={'ordering': ['weekend__round_number', '-type']},
        ),
    ]
