# Generated by Django 4.2.23 on 2025-07-25 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0038_alter_playerqualifyingmultichoice_selection_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifying',
            name='weekend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantaApp.weekend'),
        ),
        migrations.AlterField(
            model_name='race',
            name='weekend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantaApp.weekend'),
        ),
    ]
