# Generated by Django 4.2.23 on 2026-08-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0047_playerraceresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerraceresult',
            name='point_modifier',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
