# Generated by Django 4.2.23 on 2026-08-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0048_playerraceresult_point_modifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProcessingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting_for_results', 'Waiting for results'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=30)),
                ('eligible_after', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('qualifying', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_status', to='fantaApp.qualifying')),
                ('race', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_status', to='fantaApp.race')),
            ],
        ),
    ]
