# Generated by Django 4.2.23 on 2026-09-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0049_eventprocessingstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_participations', to='fantaApp.driver')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_participations', to='fantaApp.team')),
                ('weekend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='fantaApp.weekend')),
            ],
            options={
                'ordering': ['weekend__round_number', 'driver__short_name'],
                'unique_together': {('weekend', 'driver')},
            },
        ),
    ]
