# Generated by Django 4.2.23 on 2026-10-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantaApp', '0050_weekendparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceStartingGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantaApp.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_grid', to='fantaApp.race')),
            ],
            options={
                'ordering': ['race', 'position'],
                'unique_together': {('race', 'driver')},
            },
        ),
    ]
